Improve list item parsing and indented code blocks parsing
dillonkearns/elm-markdown pull request #88
Opened 2021-06-20 17:55 UTC by LutSa

What's in this PR:
1. solve the issue of #59 by using the technique of Open/Closed Blocks
2. change the UnorderedList type to a block container like BlockQuote
3. associate indent information to unordered list item and allow some nest specs according to the indent (and solve #81)
4. solve some minimal failing test cases about list item parsing by the way
5. fix minor failing test cases about “Indented code blocks” by allowing blank line between chunks

2021-07-19 18:07 UTC, dillonkearns commented
It's nice that the actual renderer functions that users write won't actual need to change.
I discussed this design a while ago with @klaftertief and we could never fully decide on where the loose/tight list item rendering responsibility should be. Loose/tight handling be done at one of two levels:

1) within the user's renderer functions, or
2) in the code that calls the user's renderer functions

The implementation you have here uses approach (2). The logic lives outside the user's renderer functions. It's nice to see the full implementation, it makes it easier for me to understand which approach I like more. And seeing your implementation, my initial feeling is that I like this approach. It would seem very low-level if the user had to handle those details of loose/tight, and I imagine that most users would just find it frustrating, and wouldn't really find it useful to be able to customize how the render based on loose/tight, but instead would just want that detail taken care of in the implementation.

It looks like remark has a similar design. You can see in this example that they parse lists as `spread: true` for loose lists and `spread: false` for tight lists: https://astexplorer.net/#/gist/0a92bbf654aca4fdfb3f139254cf0bad/fe0a57596d677919245eca2b032c2a5ca892ec85.

And since the user can map over items in the parsed Markdown Blocks, they also have the option to transform blocks and change whether a list is loose or tight, that gives at least some customizability there if it's needed.

2021-07-19 18:26 UTC, dillonkearns commented
For future reference, I thought of a 3rd design idea for how to handle loose/tight lists.

3. By default, automatically use the `paragraph` renderer to wrap loose paragraphs (as the current implementation does). Or, if a `looseListWrapper` is provided (`Just` value instead of `Nothing`), then use that to customize how to wrap loose lists.

I'm not sure there would be any value to approach (3) compared to the current approach, (2). I'm just including it here for future reference. If anyone can think of a use case where approach (3) would be beneficial, I would love to hear about it, though!

2021-08-18 14:31 UTC, LutSa commented
I’ve let all test cases passed. But since I’ve changed the parser in UnorderedList.elm and OrderedList.elm from the parser of the list to the parser of the list item, the test cases may not be so meaningful as before. Please tell me if I can improve the test cases somehow.

2021-08-19 15:51 UTC, dillonkearns commented
Excellent! I think it would be nice to have those unit tests exercising the full list parsing, so since that logic has moved up a level I made a commit to run the full parser on those test cases to keep them meaningful: d5d1e1334cf5c4b9dc7fcf7acd5cfc5895b505e1.

I think that's a good balance that will keep giving us confidence about those corner cases with the new parsing, so I think the tests are in good shape now 👍

2021-08-19 16:12 UTC, dillonkearns requested changes

2021-08-19 16:12 UTC, dillonkearns commented on src/Markdown/Block.elm
> +    | UnorderedList Bool (List (ListItem Block))
I went ahead and changed out the Bool's in the Block type, and I think it's looking good! So this is resolved now ✅

2021-08-19 18:03 UTC, dillonkearns commented on src/Markdown/ListItem.elm
> +    | EmptyItem
Actually, I see that I was mistaken about this being user-facing. This is an internal type, so the user-facing types `Markdown.Block` aren't effected by this. So this is good as is 👍

2021-08-19 18:09 UTC, dillonkearns commented on test-results/failing/New/adjacent_lists.md
> +<ul><li>This should be</li><li>An unordered list</li></ul><ol></ol><ol start="2"></ol>
I figured out what was going on! It was an issue with the test runner. It looks like it wasn't deleting these files, so they got committed but don't didn't deleted even though they are passing now. This is in good shape now 👍

2021-08-20 15:28 UTC, dillonkearns approved these changes

2021-08-20 15:29 UTC, merged

2021-08-20 15:29 UTC, dillonkearns commented
It's all looking good to me now! Thanks so much for the hard work @LutSa! 🎉